increased supported blockids to 65792
GTNewHorizons/Schematica pull request #25
Opened 2024-12-07 10:50 UTC by Fabboz

I found a little trick to overcome the 4069 block id limit. 
All previous schematics must be erased because the data is stored in a completely different way.

2024-12-07 13:31 UTC, mist475 requested changes
Gtnh schematica is also used outside of gtnh (passive support).
If I understand what you said correctly this would break any existing schematics right?
If so, please make it able to still read old schematics and make it possible to differentiate between the old and the new format. You can achieve this by adding an extra nbt tag to schematics that use the new format and checking if that tag is present before trying to parse the schematic.
This would also break compatibility with world edit and any other tools that also use the .schematic format. Maybe this should be a config option (default can be true, as long as it can be turned off so people that rely on external tools can still use this version)

2024-12-07 14:11 UTC, Fabboz commented
> Gtnh schematica is also used outside of gtnh (passive support). If I understand what you said correctly this would break any existing schematics right? If so, please make it able to still read old schematics and make it possible to differentiate between the old and the new format. You can achieve this by adding an extra nbt tag to schematics that use the new format and checking if that tag is present before trying to parse the schematic. This would also break compatibility with world edit and any other tools that also use the .schematic format. Maybe this should be a config option (default can be true, as long as it can be turned off so people that rely on external tools can still use this version)

Yes it breaks all the schematics and from what you tell me they no longer represent their standard.
They can only be read by mods that make these changes.
However, to convert the schematics of the previous version you need to create a specific mod, and the new ones created can only be read by the mods that make these changes.
If there is a piece of code that updates ids using GameRegistry.findBlock I don't know where it is.

2024-12-08 10:37 UTC, Fabboz commented
concluding the discussion I can create a config that allows you to choose before startup whether to use the old or new system combined with the creation of a different file extension. I'll do this.

2024-12-08 17:59 UTC, mist475 commented
![image](https://github.com/user-attachments/assets/eaf007f8-907b-475f-b81c-e9a2aa40140b)
From discord:
https://discord.com/channels/181078474394566657/603348502637969419/1315346626981924956 (gtnh dev channel)

2024-12-08 21:38 UTC, Fabboz commented
I made the changes.
I have no idea how neid works.

2024-12-10 01:10 UTC, PlayfulPiano commented
Is this the reason why some schematics are not recognized (e.g. eio conduits, lp pipes)?

2024-12-10 23:48 UTC, Fabboz commented
Only vanilla blocks have the same id in every world. For modded blocks they can change depending on the sequence in which the mods are loaded. So it may be that in one modpack the EIO conduits have an id of 7000 and in another 4000. Besides this, in the classic schematics if the id exceeds a certain limit a wrong one is stored.

2024-12-11 00:45 UTC, PlayfulPiano commented
> Only vanilla blocks have the same id in every world. For modded blocks they can change depending on the sequence in which the mods are loaded. So it may be that in one modpack the EIO conduits have an id of 7000 and in another 4000. Besides this, in the classic schematics if the id exceeds a certain limit a wrong one is stored.

Do you happen to have a built jar with these commits so I can test? I tried doing a build but it failed on spotless.

2024-12-11 00:57 UTC, RecursivePineapple commented
@PlayfulPiano I just allowed the workflow to run and it generated a few jars in a zip file. I'm not sure if these'll work, but you can try them.

https://github.com/GTNewHorizons/Schematica/actions/runs/12225450497?pr=25

2024-12-11 01:06 UTC, PlayfulPiano commented
> @PlayfulPiano I just allowed the workflow to run and it generated a few jars in a zip file. I'm not sure if these'll work, but you can try them.
> 
> https://github.com/GTNewHorizons/Schematica/actions/runs/12225450497?pr=25

damn, looks like the issue is separate then. oh well, was hoping.
![image](https://github.com/user-attachments/assets/ec5a7745-1671-4097-acca-a3f926bd7bcd)

2024-12-11 01:14 UTC, PlayfulPiano commented
Also, my recommendation would be to include a toggle between the two formatting types within the load schematic gui, and maybe include a message popup if it comes up blank for the current format but there exists the other format in the folder. That way, if people want to start switching over to the new formatting, they both will see visibly that it exists and if the default format changes, also warn why old schematics aren't showing up.

2024-12-11 04:15 UTC, Fabboz commented
@PlayfulPiano check the material list in manipolation gui.

2024-12-11 04:16 UTC, Fabboz commented
> Also, my recommendation would be to include a toggle between the two formatting types within the load schematic gui (plus an easy toggle in the save schematic gui), and maybe include a message popup if it comes up blank for the current format but there exists the other format in the folder. That way, if people want to start switching over to the new formatting, they both will see visibly that it exists and if the default format changes, also warn why old schematics aren't showing up.

I dont know how i can do that.

2024-12-11 14:52 UTC, PlayfulPiano commented
> @PlayfulPiano check the material list in manipolation gui.

unsure what you mean by manipolation but if you're referring to the materials list, it doesn't show there either.


> > Also, my recommendation would be to include a toggle between the two formatting types within the load schematic gui (plus an easy toggle in the save schematic gui), and maybe include a message popup if it comes up blank for the current format but there exists the other format in the folder. That way, if people want to start switching over to the new formatting, they both will see visibly that it exists and if the default format changes, also warn why old schematics aren't showing up.
> 
> I dont know how i can do that.

Ah, I see, in that case maybe someone could try to PR after this one for that implementation.

2024-12-11 15:32 UTC, Fabboz commented
> > @PlayfulPiano check the material list in manipolation gui.
> 
> unsure what you mean by manipolation but if you're referring to the materials list, it doesn't show there either.
> 
Could be a tile entity.

2025-01-18 12:26 UTC, mist475 commented
assuming this has been well tested, no objections by me anymore. Using the neid format is probably a better idea but in the meantime this will probably be fine

2025-01-18 12:26 UTC, mist475 approved these changes

2025-01-18 13:14 UTC, merged